### ISSUE TITLE
can't import repo

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/ash-nazg#111]
Trying to import: 
https://github.com/WICG/cq-usecases

I get an error:
![screenshot 2018-01-16 11 36 52](https://user-images.githubusercontent.com/870154/34966707-c0bf72c2-fab1-11e7-93f4-430d8276cfaf.png)

I noticed that there is also a 500 error happening on the server: 

```JS
TypeError: Cannot read property &#39;name&#39; of undefined<br> &nbsp; &nbsp;at andify (/u/lab/ash-nazg/gh.js:58:82)<br> &nbsp; &nbsp;at Object.createOrImportRepo (/u/lab/ash-nazg/gh.js:135:33)<br> &nbsp; &nbsp;at Object.importRepo (/u/lab/ash-nazg/gh.js:110:14)<br> &nbsp; &nbsp;at /u/lab/ash-nazg/server.js:236:31<br> &nbsp; &nbsp;at /u/lab/ash-nazg/node_modules/async/dist/async.js:1012:9<br> &nbsp; &nbsp;at /u/lab/ash-nazg/node_modules/async/dist/async.js:359:16<br> &nbsp; &nbsp;at eachOfArrayLike (/u/lab/ash-nazg/node_modules/async/dist/async.js:928:9)<br> &nbsp; &nbsp;at eachOf (/u/lab/ash-nazg/node_modules/async/dist/async.js:990:5)<br> &nbsp; &nbsp;at _asyncMap (/u/lab/ash-nazg/node_modules/async/dist/async.js:1005:5)<br> &nbsp; &nbsp;at Object.map (/u/lab/ash-nazg/node_modules/async/dist/async.js:995:16)
```

Could someone kindly please import it for me?

**Comment by dontcallmedom** [comment]
I have done the importing, and am hunting the underlying bug; for sake of completeness, which browser were you using when the error happened?

**Comment by marcoscaceres** [comment]
Tried in Safari and Chrome I think.
