### ISSUE TITLE
"Database does not exist" error

### ISSUE THREAD

**Issue by yoavweiss** [w3c/ash-nazg#151]
Going to https://labs.w3.org/repo-manager/ I'm getting the following error

```
CouchError: not_found: Database does not exist.
    at Request._onResponse [as _callback] (/u/ash-nazg/node_modules/cradle/lib/cradle.js:241:29)
    at Request.self.callback (/u/ash-nazg/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/u/ash-nazg/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/u/ash-nazg/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```
So, it seems like something is off... :/

**Comment by dontcallmedom** [comment]
thanks for the notice - @deniak fixed it (it was a db upgrade gone awry apparently)

**Comment by yoavweiss** [comment]
Thanks for fixing! :)
