### ISSUE TITLE
Can't import repo?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/ash-nazg#55]
Getting a 500 error importing a repo:

```
TypeError: Cannot read property &#39;name&#39; of undefined<br> &nbsp; &nbsp;at andify (/u/lab/ash-nazg/gh.js:69:82)<br> &nbsp; &nbsp;at Object.GH.createOrImportRepo (/u/lab/ash-nazg/gh.js:112:33)<br> &nbsp; &nbsp;at Object.GH.importRepo (/u/lab/ash-nazg/gh.js:90:14)<br> &nbsp; &nbsp;at /u/lab/ash-nazg/server.js:217:31<br> &nbsp; &nbsp;at /u/lab/ash-nazg/node_modules/async/dist/async.js:486:20<br> &nbsp; &nbsp;at /u/lab/ash-nazg/node_modules/async/dist/async.js:1074:13<br> &nbsp; &nbsp;at /u/lab/ash-nazg/node_modules/async/dist/async.js:952:25<br> &nbsp; &nbsp;at eachOfArrayLike (/u/lab/ash-nazg/node_modules/async/dist/async.js:990:13)<br> &nbsp; &nbsp;at eachOf (/u/lab/ash-nazg/node_modules/async/dist/async.js:1052:9)<br> &nbsp; &nbsp;at _asyncMap (/u/lab/ash-nazg/node_modules/async/dist/async.js:1067:9)
```

Repo I was trying to import: 
https://github.com/WICG/memory-pressure/

**Comment by marcoscaceres** [comment]
That should have been *can't* :)

**Comment by dontcallmedom** [comment]
@marcoscaceres I am having trouble reproducing this; could you give me admin rights on the WICG org (at least on this repo) for me to test this particular case?

**Comment by marcoscaceres** [comment]
Invite sent. I made you an owner, as I think it would be good to have a w3c person as owner.

**Comment by dontcallmedom** [comment]
hmm... the good news is that I have successfully imported the repo, the bad news is that I'm none the wiser as to why it failed for you…

**Comment by marcoscaceres** [comment]
odd... oh well. Let's close with WFM. I'll reopen if it happens again.
